create table public.companies (
    id bigint generated by default as identity primary key,

    ticker text not null,
    company_name text not null,

    exchange text,
    sector text,
    industry text,

    cik text,
    country text default 'US',
    currency text default 'USD',

    is_active boolean not null default true,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint companies_ticker_unique unique (ticker)
);

create index companies_sector_idx
    on public.companies (sector);

create index companies_industry_idx
    on public.companies (industry);